# Generated by Django 4.1.1 on 2022-10-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_discount_remove_order_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_date',
        ),
    ]
