# Generated by Django 4.1.1 on 2022-09-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('package', models.CharField(max_length=32)),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=32)),
                ('picture', models.ImageField(upload_to='', verbose_name='Picture of Product')),
                ('country', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
            ],
        ),
    ]
